/*
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
}
