/*
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import rasman.robot.mars.des.ui.internal.DesActivator;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DesActivator.getInstance().getInjector("rasman.robot.mars.des.Dsl");
	}

}
