/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.validation;

import rasman.robot.mars.des.validation.AbstractDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
