/*
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
