/*
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("rasman/robot/mars/des/parser/antlr/internal/InternalDsl.tokens");
	}
}
