/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des;

import rasman.robot.mars.des.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
