/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rasman.robot.mars.des.dsl.ColorSensor#isDistinct <em>Distinct</em>}</li>
 *   <li>{@link rasman.robot.mars.des.dsl.ColorSensor#getKey <em>Key</em>}</li>
 *   <li>{@link rasman.robot.mars.des.dsl.ColorSensor#getKeys <em>Keys</em>}</li>
 * </ul>
 *
 * @see rasman.robot.mars.des.dsl.DslPackage#getColorSensor()
 * @model
 * @generated
 */
public interface ColorSensor extends SensorType
{
  /**
   * Returns the value of the '<em><b>Distinct</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distinct</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distinct</em>' attribute.
   * @see #setDistinct(boolean)
   * @see rasman.robot.mars.des.dsl.DslPackage#getColorSensor_Distinct()
   * @model
   * @generated
   */
  boolean isDistinct();

  /**
   * Sets the value of the '{@link rasman.robot.mars.des.dsl.ColorSensor#isDistinct <em>Distinct</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distinct</em>' attribute.
   * @see #isDistinct()
   * @generated
   */
  void setDistinct(boolean value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(ColorValue)
   * @see rasman.robot.mars.des.dsl.DslPackage#getColorSensor_Key()
   * @model containment="true"
   * @generated
   */
  ColorValue getKey();

  /**
   * Sets the value of the '{@link rasman.robot.mars.des.dsl.ColorSensor#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(ColorValue value);

  /**
   * Returns the value of the '<em><b>Keys</b></em>' containment reference list.
   * The list contents are of type {@link rasman.robot.mars.des.dsl.ColorValue}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keys</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys</em>' containment reference list.
   * @see rasman.robot.mars.des.dsl.DslPackage#getColorSensor_Keys()
   * @model containment="true"
   * @generated
   */
  EList<ColorValue> getKeys();

} // ColorSensor
