/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rasman.robot.mars.des.dsl.ColorValue#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see rasman.robot.mars.des.dsl.DslPackage#getColorValue()
 * @model
 * @generated
 */
public interface ColorValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link rasman.robot.mars.des.dsl.Colors}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see rasman.robot.mars.des.dsl.Colors
   * @see #setColor(Colors)
   * @see rasman.robot.mars.des.dsl.DslPackage#getColorValue_Color()
   * @model
   * @generated
   */
  Colors getColor();

  /**
   * Sets the value of the '{@link rasman.robot.mars.des.dsl.ColorValue#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see rasman.robot.mars.des.dsl.Colors
   * @see #getColor()
   * @generated
   */
  void setColor(Colors value);

} // ColorValue
