/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see rasman.robot.mars.des.dsl.DslPackage
 * @generated
 */
public interface DslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslFactory eINSTANCE = rasman.robot.mars.des.dsl.impl.DslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mission</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mission</em>'.
   * @generated
   */
  Mission createMission();

  /**
   * Returns a new object of class '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task</em>'.
   * @generated
   */
  Task createTask();

  /**
   * Returns a new object of class '<em>time Unit Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>time Unit Value</em>'.
   * @generated
   */
  timeUnitValue createtimeUnitValue();

  /**
   * Returns a new object of class '<em>Ignorables</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ignorables</em>'.
   * @generated
   */
  Ignorables createIgnorables();

  /**
   * Returns a new object of class '<em>Sensor Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Type</em>'.
   * @generated
   */
  SensorType createSensorType();

  /**
   * Returns a new object of class '<em>Color Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color Sensor</em>'.
   * @generated
   */
  ColorSensor createColorSensor();

  /**
   * Returns a new object of class '<em>Touch Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Touch Sensor</em>'.
   * @generated
   */
  TouchSensor createTouchSensor();

  /**
   * Returns a new object of class '<em>Ultrasonic Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ultrasonic Sensor</em>'.
   * @generated
   */
  UltrasonicSensor createUltrasonicSensor();

  /**
   * Returns a new object of class '<em>Color Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color Value</em>'.
   * @generated
   */
  ColorValue createColorValue();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DslPackage getDslPackage();

} //DslFactory
