/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see rasman.robot.mars.des.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.robot.rasman/mars/des/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = rasman.robot.mars.des.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.MissionImpl <em>Mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.MissionImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getMission()
   * @generated
   */
  int MISSION = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TASKS = 0;

  /**
   * The number of structural features of the '<em>Mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.TaskImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getTask()
   * @generated
   */
  int TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__SENSOR = 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTION = 2;

  /**
   * The feature id for the '<em><b>Nr Of Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NR_OF_TIMES = 3;

  /**
   * The feature id for the '<em><b>Ignore Behavior</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__IGNORE_BEHAVIOR = 4;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TIME = 5;

  /**
   * The feature id for the '<em><b>Timeunit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TIMEUNIT = 6;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.timeUnitValueImpl <em>time Unit Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.timeUnitValueImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#gettimeUnitValue()
   * @generated
   */
  int TIME_UNIT_VALUE = 2;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_UNIT_VALUE__UNIT = 0;

  /**
   * The number of structural features of the '<em>time Unit Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_UNIT_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.IgnorablesImpl <em>Ignorables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.IgnorablesImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getIgnorables()
   * @generated
   */
  int IGNORABLES = 3;

  /**
   * The feature id for the '<em><b>AVOID OBJECTS</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IGNORABLES__AVOID_OBJECTS = 0;

  /**
   * The number of structural features of the '<em>Ignorables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IGNORABLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.SensorTypeImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getSensorType()
   * @generated
   */
  int SENSOR_TYPE = 4;

  /**
   * The number of structural features of the '<em>Sensor Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.ColorSensorImpl <em>Color Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.ColorSensorImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getColorSensor()
   * @generated
   */
  int COLOR_SENSOR = 5;

  /**
   * The feature id for the '<em><b>Distinct</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENSOR__DISTINCT = SENSOR_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENSOR__KEY = SENSOR_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Keys</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENSOR__KEYS = SENSOR_TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Color Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENSOR_FEATURE_COUNT = SENSOR_TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.TouchSensorImpl <em>Touch Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.TouchSensorImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getTouchSensor()
   * @generated
   */
  int TOUCH_SENSOR = 6;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_SENSOR__KEY = SENSOR_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Touch Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_SENSOR_FEATURE_COUNT = SENSOR_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.UltrasonicSensorImpl <em>Ultrasonic Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.UltrasonicSensorImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getUltrasonicSensor()
   * @generated
   */
  int ULTRASONIC_SENSOR = 7;

  /**
   * The feature id for the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRASONIC_SENSOR__COMPARATOR = SENSOR_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRASONIC_SENSOR__DISTANCE = SENSOR_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ultrasonic Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRASONIC_SENSOR_FEATURE_COUNT = SENSOR_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.impl.ColorValueImpl <em>Color Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.impl.ColorValueImpl
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getColorValue()
   * @generated
   */
  int COLOR_VALUE = 8;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_VALUE__COLOR = 0;

  /**
   * The number of structural features of the '<em>Color Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.timeUnit <em>time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.timeUnit
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#gettimeUnit()
   * @generated
   */
  int TIME_UNIT = 9;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.TouchSensorSides <em>Touch Sensor Sides</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.TouchSensorSides
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getTouchSensorSides()
   * @generated
   */
  int TOUCH_SENSOR_SIDES = 10;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.Actions <em>Actions</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.Actions
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getActions()
   * @generated
   */
  int ACTIONS = 11;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.Directions <em>Directions</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.Directions
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getDirections()
   * @generated
   */
  int DIRECTIONS = 12;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.Colors <em>Colors</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.Colors
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getColors()
   * @generated
   */
  int COLORS = 13;

  /**
   * The meta object id for the '{@link rasman.robot.mars.des.dsl.CompareOperator <em>Compare Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rasman.robot.mars.des.dsl.CompareOperator
   * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getCompareOperator()
   * @generated
   */
  int COMPARE_OPERATOR = 14;


  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.Mission <em>Mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mission</em>'.
   * @see rasman.robot.mars.des.dsl.Mission
   * @generated
   */
  EClass getMission();

  /**
   * Returns the meta object for the containment reference list '{@link rasman.robot.mars.des.dsl.Mission#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see rasman.robot.mars.des.dsl.Mission#getTasks()
   * @see #getMission()
   * @generated
   */
  EReference getMission_Tasks();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see rasman.robot.mars.des.dsl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the containment reference '{@link rasman.robot.mars.des.dsl.Task#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sensor</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getSensor()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Sensor();

  /**
   * Returns the meta object for the attribute list '{@link rasman.robot.mars.des.dsl.Task#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Action</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getAction()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Action();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.Task#getNrOfTimes <em>Nr Of Times</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nr Of Times</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getNrOfTimes()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_NrOfTimes();

  /**
   * Returns the meta object for the containment reference '{@link rasman.robot.mars.des.dsl.Task#getIgnoreBehavior <em>Ignore Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ignore Behavior</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getIgnoreBehavior()
   * @see #getTask()
   * @generated
   */
  EReference getTask_IgnoreBehavior();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.Task#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getTime()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Time();

  /**
   * Returns the meta object for the containment reference '{@link rasman.robot.mars.des.dsl.Task#getTimeunit <em>Timeunit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Timeunit</em>'.
   * @see rasman.robot.mars.des.dsl.Task#getTimeunit()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Timeunit();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.timeUnitValue <em>time Unit Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>time Unit Value</em>'.
   * @see rasman.robot.mars.des.dsl.timeUnitValue
   * @generated
   */
  EClass gettimeUnitValue();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.timeUnitValue#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see rasman.robot.mars.des.dsl.timeUnitValue#getUnit()
   * @see #gettimeUnitValue()
   * @generated
   */
  EAttribute gettimeUnitValue_Unit();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.Ignorables <em>Ignorables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ignorables</em>'.
   * @see rasman.robot.mars.des.dsl.Ignorables
   * @generated
   */
  EClass getIgnorables();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.Ignorables#getAVOID_OBJECTS <em>AVOID OBJECTS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>AVOID OBJECTS</em>'.
   * @see rasman.robot.mars.des.dsl.Ignorables#getAVOID_OBJECTS()
   * @see #getIgnorables()
   * @generated
   */
  EAttribute getIgnorables_AVOID_OBJECTS();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.SensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Type</em>'.
   * @see rasman.robot.mars.des.dsl.SensorType
   * @generated
   */
  EClass getSensorType();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.ColorSensor <em>Color Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color Sensor</em>'.
   * @see rasman.robot.mars.des.dsl.ColorSensor
   * @generated
   */
  EClass getColorSensor();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.ColorSensor#isDistinct <em>Distinct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distinct</em>'.
   * @see rasman.robot.mars.des.dsl.ColorSensor#isDistinct()
   * @see #getColorSensor()
   * @generated
   */
  EAttribute getColorSensor_Distinct();

  /**
   * Returns the meta object for the containment reference '{@link rasman.robot.mars.des.dsl.ColorSensor#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Key</em>'.
   * @see rasman.robot.mars.des.dsl.ColorSensor#getKey()
   * @see #getColorSensor()
   * @generated
   */
  EReference getColorSensor_Key();

  /**
   * Returns the meta object for the containment reference list '{@link rasman.robot.mars.des.dsl.ColorSensor#getKeys <em>Keys</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Keys</em>'.
   * @see rasman.robot.mars.des.dsl.ColorSensor#getKeys()
   * @see #getColorSensor()
   * @generated
   */
  EReference getColorSensor_Keys();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.TouchSensor <em>Touch Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Touch Sensor</em>'.
   * @see rasman.robot.mars.des.dsl.TouchSensor
   * @generated
   */
  EClass getTouchSensor();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.TouchSensor#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see rasman.robot.mars.des.dsl.TouchSensor#getKey()
   * @see #getTouchSensor()
   * @generated
   */
  EAttribute getTouchSensor_Key();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.UltrasonicSensor <em>Ultrasonic Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ultrasonic Sensor</em>'.
   * @see rasman.robot.mars.des.dsl.UltrasonicSensor
   * @generated
   */
  EClass getUltrasonicSensor();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.UltrasonicSensor#getComparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparator</em>'.
   * @see rasman.robot.mars.des.dsl.UltrasonicSensor#getComparator()
   * @see #getUltrasonicSensor()
   * @generated
   */
  EAttribute getUltrasonicSensor_Comparator();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.UltrasonicSensor#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see rasman.robot.mars.des.dsl.UltrasonicSensor#getDistance()
   * @see #getUltrasonicSensor()
   * @generated
   */
  EAttribute getUltrasonicSensor_Distance();

  /**
   * Returns the meta object for class '{@link rasman.robot.mars.des.dsl.ColorValue <em>Color Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color Value</em>'.
   * @see rasman.robot.mars.des.dsl.ColorValue
   * @generated
   */
  EClass getColorValue();

  /**
   * Returns the meta object for the attribute '{@link rasman.robot.mars.des.dsl.ColorValue#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see rasman.robot.mars.des.dsl.ColorValue#getColor()
   * @see #getColorValue()
   * @generated
   */
  EAttribute getColorValue_Color();

  /**
   * Returns the meta object for enum '{@link rasman.robot.mars.des.dsl.timeUnit <em>time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>time Unit</em>'.
   * @see rasman.robot.mars.des.dsl.timeUnit
   * @generated
   */
  EEnum gettimeUnit();

  /**
   * Returns the meta object for enum '{@link rasman.robot.mars.des.dsl.TouchSensorSides <em>Touch Sensor Sides</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Touch Sensor Sides</em>'.
   * @see rasman.robot.mars.des.dsl.TouchSensorSides
   * @generated
   */
  EEnum getTouchSensorSides();

  /**
   * Returns the meta object for enum '{@link rasman.robot.mars.des.dsl.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Actions</em>'.
   * @see rasman.robot.mars.des.dsl.Actions
   * @generated
   */
  EEnum getActions();

  /**
   * Returns the meta object for enum '{@link rasman.robot.mars.des.dsl.Directions <em>Directions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Directions</em>'.
   * @see rasman.robot.mars.des.dsl.Directions
   * @generated
   */
  EEnum getDirections();

  /**
   * Returns the meta object for enum '{@link rasman.robot.mars.des.dsl.Colors <em>Colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Colors</em>'.
   * @see rasman.robot.mars.des.dsl.Colors
   * @generated
   */
  EEnum getColors();

  /**
   * Returns the meta object for enum '{@link rasman.robot.mars.des.dsl.CompareOperator <em>Compare Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Compare Operator</em>'.
   * @see rasman.robot.mars.des.dsl.CompareOperator
   * @generated
   */
  EEnum getCompareOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.MissionImpl <em>Mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.MissionImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getMission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getMission();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TASKS = eINSTANCE.getMission_Tasks();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.TaskImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__SENSOR = eINSTANCE.getTask_Sensor();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__ACTION = eINSTANCE.getTask_Action();

    /**
     * The meta object literal for the '<em><b>Nr Of Times</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NR_OF_TIMES = eINSTANCE.getTask_NrOfTimes();

    /**
     * The meta object literal for the '<em><b>Ignore Behavior</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__IGNORE_BEHAVIOR = eINSTANCE.getTask_IgnoreBehavior();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TIME = eINSTANCE.getTask_Time();

    /**
     * The meta object literal for the '<em><b>Timeunit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__TIMEUNIT = eINSTANCE.getTask_Timeunit();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.timeUnitValueImpl <em>time Unit Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.timeUnitValueImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#gettimeUnitValue()
     * @generated
     */
    EClass TIME_UNIT_VALUE = eINSTANCE.gettimeUnitValue();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_UNIT_VALUE__UNIT = eINSTANCE.gettimeUnitValue_Unit();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.IgnorablesImpl <em>Ignorables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.IgnorablesImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getIgnorables()
     * @generated
     */
    EClass IGNORABLES = eINSTANCE.getIgnorables();

    /**
     * The meta object literal for the '<em><b>AVOID OBJECTS</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IGNORABLES__AVOID_OBJECTS = eINSTANCE.getIgnorables_AVOID_OBJECTS();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.SensorTypeImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getSensorType()
     * @generated
     */
    EClass SENSOR_TYPE = eINSTANCE.getSensorType();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.ColorSensorImpl <em>Color Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.ColorSensorImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getColorSensor()
     * @generated
     */
    EClass COLOR_SENSOR = eINSTANCE.getColorSensor();

    /**
     * The meta object literal for the '<em><b>Distinct</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_SENSOR__DISTINCT = eINSTANCE.getColorSensor_Distinct();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLOR_SENSOR__KEY = eINSTANCE.getColorSensor_Key();

    /**
     * The meta object literal for the '<em><b>Keys</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLOR_SENSOR__KEYS = eINSTANCE.getColorSensor_Keys();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.TouchSensorImpl <em>Touch Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.TouchSensorImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getTouchSensor()
     * @generated
     */
    EClass TOUCH_SENSOR = eINSTANCE.getTouchSensor();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOUCH_SENSOR__KEY = eINSTANCE.getTouchSensor_Key();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.UltrasonicSensorImpl <em>Ultrasonic Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.UltrasonicSensorImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getUltrasonicSensor()
     * @generated
     */
    EClass ULTRASONIC_SENSOR = eINSTANCE.getUltrasonicSensor();

    /**
     * The meta object literal for the '<em><b>Comparator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ULTRASONIC_SENSOR__COMPARATOR = eINSTANCE.getUltrasonicSensor_Comparator();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ULTRASONIC_SENSOR__DISTANCE = eINSTANCE.getUltrasonicSensor_Distance();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.impl.ColorValueImpl <em>Color Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.impl.ColorValueImpl
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getColorValue()
     * @generated
     */
    EClass COLOR_VALUE = eINSTANCE.getColorValue();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_VALUE__COLOR = eINSTANCE.getColorValue_Color();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.timeUnit <em>time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.timeUnit
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#gettimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.gettimeUnit();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.TouchSensorSides <em>Touch Sensor Sides</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.TouchSensorSides
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getTouchSensorSides()
     * @generated
     */
    EEnum TOUCH_SENSOR_SIDES = eINSTANCE.getTouchSensorSides();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.Actions <em>Actions</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.Actions
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getActions()
     * @generated
     */
    EEnum ACTIONS = eINSTANCE.getActions();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.Directions <em>Directions</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.Directions
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getDirections()
     * @generated
     */
    EEnum DIRECTIONS = eINSTANCE.getDirections();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.Colors <em>Colors</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.Colors
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getColors()
     * @generated
     */
    EEnum COLORS = eINSTANCE.getColors();

    /**
     * The meta object literal for the '{@link rasman.robot.mars.des.dsl.CompareOperator <em>Compare Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rasman.robot.mars.des.dsl.CompareOperator
     * @see rasman.robot.mars.des.dsl.impl.DslPackageImpl#getCompareOperator()
     * @generated
     */
    EEnum COMPARE_OPERATOR = eINSTANCE.getCompareOperator();

  }

} //DslPackage
