/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see rasman.robot.mars.des.dsl.DslPackage#getSensorType()
 * @model
 * @generated
 */
public interface SensorType extends EObject
{
} // SensorType
