/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>time Unit Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rasman.robot.mars.des.dsl.timeUnitValue#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see rasman.robot.mars.des.dsl.DslPackage#gettimeUnitValue()
 * @model
 * @generated
 */
public interface timeUnitValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link rasman.robot.mars.des.dsl.timeUnit}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see rasman.robot.mars.des.dsl.timeUnit
   * @see #setUnit(timeUnit)
   * @see rasman.robot.mars.des.dsl.DslPackage#gettimeUnitValue_Unit()
   * @model
   * @generated
   */
  timeUnit getUnit();

  /**
   * Sets the value of the '{@link rasman.robot.mars.des.dsl.timeUnitValue#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see rasman.robot.mars.des.dsl.timeUnit
   * @see #getUnit()
   * @generated
   */
  void setUnit(timeUnit value);

} // timeUnitValue
