/**
 * generated by Xtext 2.10.0
 */
package rasman.robot.mars.des.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Touch Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rasman.robot.mars.des.dsl.TouchSensor#getKey <em>Key</em>}</li>
 * </ul>
 *
 * @see rasman.robot.mars.des.dsl.DslPackage#getTouchSensor()
 * @model
 * @generated
 */
public interface TouchSensor extends SensorType
{
  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * The literals are from the enumeration {@link rasman.robot.mars.des.dsl.TouchSensorSides}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see rasman.robot.mars.des.dsl.TouchSensorSides
   * @see #setKey(TouchSensorSides)
   * @see rasman.robot.mars.des.dsl.DslPackage#getTouchSensor_Key()
   * @model
   * @generated
   */
  TouchSensorSides getKey();

  /**
   * Sets the value of the '{@link rasman.robot.mars.des.dsl.TouchSensor#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see rasman.robot.mars.des.dsl.TouchSensorSides
   * @see #getKey()
   * @generated
   */
  void setKey(TouchSensorSides value);

} // TouchSensor
